# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1def360bfc7733689b7e083391183acea50e76e6f3cfcf873fea3fba5c1ed7d975af6d6b98fce19d55f9c73ba50beecd2c7ae1e36c924433bd4af660cd4881af

test:
  secret_key_base: 817a323a8b12dec5fe635d7f0c772f6f48324b48411a116e31e8cde5255b9265c4b88a74c061ceddb005aa852063ff8a46dfeab42f22ab034c590871e864edb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
