# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$(document).on 'turbolinks:load', ->
  $(".bxslider").bxSlider(slideWidth: 500, mode: 'fade',adaptiveHeight: true)


#slideWidth: 600





# ---
# generated by js2coffee 2.2.0